name: 'Test Report'

on:
  workflow_run:
    workflows: ['SUMO DEV CI']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: PR Unit Tests
        path: TEST-*.xml
        reporter: java-junit
